name: dentist_india_plus
description: "Happy Teeth, Happy You"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  simple_gradient_text: ^1.3.0
  curved_carousel: ^0.0.8
  flutter_dash: ^1.0.0
  get: ^4.6.5
  flutter_circular_text: ^0.3.1
  auto_size_text: ^3.0.0
  url_strategy: ^0.2.0
  intl: ^0.17.0
  pinput: ^4.0.0
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - res/images/
    - res/fonts/
    - res/icons/

  fonts:
    - family: BillSmith
      fonts:
        - asset: res/fonts/BillSmith.ttf
          weight: 800
    - family: KumbhsansBold
      fonts:
        - asset: res/fonts/KumbhSans-ExtraBold.ttf
          weight: 900
    - family: KumbhsansSemiBold
      fonts:
        - asset: res/fonts/KumbhSans-Bold.ttf
          weight: 800
    - family: Kumbhsans
      fonts:
        - asset: res/fonts/KumbhSans-ExtraBold.ttf
          weight: 900
        - asset: res/fonts/KumbhSans-Bold.ttf
          weight: 800
        - asset: res/fonts/KumbhSans-Medium.ttf
          weight: 700
        - asset: res/fonts/KumbhSans-Regular.ttf
          weight: 600
        - asset: res/fonts/KumbhSans-Light.ttf
          weight: 500
